print("Welcome to the Gesture Recognigition Software")
print(" ")
print("In this Software, You can do the following actions:")
print(" ")
print("1. Spidy Gesture --> It opens the Facebook Page in chrome")
print(" ")
print("2. Aashirwad Gesture --> It opens the Power point of Linux (Libre Office Impress) ")
print(" ")
print("3. Shaka Gesture --> It opens the Gedit Page ")
print(" ")
print("4. Give Gesture --> It Closes the Page ")
print("Caution: The chrome page must be open to close it")
print(" ")
print("5. Super Gesture --> It opens the Gimp software ")
print(" ")
y = input("Show the required gesture and Press Enter to continue ")